In [4]:
import pandas as pd
from sentence_transformers import SentenceTransformer, util
from tqdm import tqdm

In [6]:
df = pd.read_csv("final_dataset.csv")

In [7]:
df.head()

,resume_text,jobs
0,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nPosition: Junior PHP Dev...
1,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nPosition: Junior PHP Dev...
2,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nJob Summary:\n\nWe are s...
3,Abhishek Chaudhary \n ac5712916@gmail.com |...,Job Title: Sr. Website UI/UX Designer and Deve...
4,Abhishek Chaudhary \n ac5712916@gmail.com |...,We are looking for a passionate and enthusiast...

In [8]:
model = SentenceTransformer('all-MiniLM-L6-v2')

In [10]:
scores = []

In [12]:
for i, row in tqdm(df.iterrows(),total = len(df)):
    jd     = str(row['jobs'])
    resume = str(row['resume_text'])

    embeddings = model.encode([jd, resume], convert_to_tensor= True)

    score = util.cos_sim(embeddings[0], embeddings[1]).item()

    scores.append(round(score* 100, 2))


df['ats_score'] = scores

  0%|                                                                                         | 0/1820 [00:00<?, ?it/s]
  0%|                                                                                 | 1/1820 [00:00<09:49,  3.09it/s]
  0%|▏                                                                                | 3/1820 [00:00<04:37,  6.54it/s]
  0%|▏                                                                                | 4/1820 [00:00<04:04,  7.42it/s]
  0%|▏                                                                                | 5/1820 [00:00<03:44,  8.07it/s]
  0%|▎                                                                                | 6/1820 [00:00<03:32,  8.55it/s]
  0%|▎                                                                                | 8/1820 [00:01<03:13,  9.35it/s]
  0%|▍                                                                                | 9/1820 [00:01<03:13,  9.35it/s]
  1%|▍                                                                               | 10/1820 [00:01<03:11,  9.45it/s]
  1%|▌                                                                               | 12/1820 [00:01<03:00, 10.04it/s]
  1%|▌                                                                               | 14/1820 [00:01<02:52, 10.44it/s]
  1%|▋                                                                               | 16/1820 [00:01<02:47, 10.75it/s]
  1%|▊                                                                               | 18/1820 [00:01<02:43, 11.00it/s]
  1%|▉                                                                               | 20/1820 [00:02<02:42, 11.05it/s]
  1%|▉                                                                               | 22/1820 [00:02<02:40, 11.18it/s]
  1%|█                                                                               | 24/1820 [00:02<02:41, 11.12it/s]
  1%|█▏                                                                              | 26/1820 [00:02<02:40, 11.15it/s]
  2%|█▏                                                                              | 28/1820 [00:02<02:39, 11.26it/s]
  2%|█▎                                                                              | 30/1820 [00:03<02:41, 11.08it/s]
  2%|█▍                                                                              | 32/1820 [00:03<02:38, 11.27it/s]
  2%|█▍                                                                              | 34/1820 [00:03<02:38, 11.28it/s]
  2%|█▌                                                                              | 36/1820 [00:03<02:35, 11.44it/s]
  2%|█▋                                                                              | 38/1820 [00:03<02:33, 11.57it/s]
  2%|█▊                                                                              | 40/1820 [00:03<02:40, 11.11it/s]
  2%|█▊                                                                              | 42/1820 [00:04<02:38, 11.22it/s]
  2%|█▉                                                                              | 44/1820 [00:04<02:36, 11.32it/s]
  3%|██                                                                              | 46/1820 [00:04<02:35, 11.43it/s]
  3%|██                                                                              | 48/1820 [00:04<02:33, 11.57it/s]
  3%|██▏                                                                             | 50/1820 [00:04<02:31, 11.71it/s]
  3%|██▎                                                                             | 52/1820 [00:04<02:31, 11.70it/s]
  3%|██▎                                                                             | 54/1820 [00:05<02:33, 11.48it/s]
  3%|██▍                                                                             | 56/1820 [00:05<02:35, 11.32it/s]
  3%|██▌                                                                             | 58/1820 [00:05<02:35, 11.36it/s]
  3%|██▋                                                                             | 60/1820 [00:05<02:37, 11.20it/s]
  3%|██▋                                                                             | 62/1820 [00:05<02:38, 11.10it/s]
  4%|██▊                                                                             | 64/1820 [00:05<02:34, 11.36it/s]
  4%|██▉                                                                             | 66/1820 [00:06<02:30, 11.64it/s]
  4%|██▉                                                                             | 68/1820 [00:06<02:31, 11.59it/s]
  4%|███                                                                             | 70/1820 [00:06<02:32, 11.44it/s]
  4%|███▏                                                                            | 72/1820 [00:06<02:35, 11.21it/s]
  4%|███▎                                                                            | 74/1820 [00:06<02:33, 11.40it/s]
  4%|███▎                                                                            | 76/1820 [00:07<02:31, 11.54it/s]
  4%|███▍                                                                            | 78/1820 [00:07<02:30, 11.60it/s]
  4%|███▌                                                                            | 80/1820 [00:07<02:29, 11.62it/s]
  5%|███▌                                                                            | 82/1820 [00:07<02:37, 11.06it/s]
  5%|███▋                                                                            | 84/1820 [00:07<02:35, 11.17it/s]
  5%|███▊                                                                            | 86/1820 [00:07<02:34, 11.23it/s]
  5%|███▊                                                                            | 88/1820 [00:08<02:34, 11.21it/s]
  5%|███▉                                                                            | 90/1820 [00:08<02:32, 11.33it/s]
  5%|████                                                                            | 92/1820 [00:08<02:36, 11.01it/s]
  5%|████▏                                                                           | 94/1820 [00:08<02:36, 11.04it/s]
  5%|████▏                                                                           | 96/1820 [00:08<02:34, 11.15it/s]
  5%|████▎                                                                           | 98/1820 [00:08<02:31, 11.33it/s]
  5%|████▎                                                                          | 100/1820 [00:09<02:32, 11.29it/s]
  6%|████▍                                                                          | 102/1820 [00:09<02:31, 11.33it/s]
  6%|████▌                                                                          | 104/1820 [00:09<02:32, 11.26it/s]
  6%|████▌                                                                          | 106/1820 [00:09<02:31, 11.34it/s]
  6%|████▋                                                                          | 108/1820 [00:09<02:30, 11.39it/s]
  6%|████▊                                                                          | 110/1820 [00:10<02:32, 11.22it/s]
  6%|████▊                                                                          | 112/1820 [00:10<02:32, 11.18it/s]
  6%|████▉                                                                          | 114/1820 [00:10<02:30, 11.30it/s]
  6%|█████                                                                          | 116/1820 [00:10<02:35, 10.94it/s]
  6%|█████                                                                          | 118/1820 [00:10<02:33, 11.08it/s]
  7%|█████▏                                                                         | 120/1820 [00:10<02:28, 11.45it/s]
  7%|█████▎                                                                         | 122/1820 [00:11<02:27, 11.50it/s]
  7%|█████▍                                                                         | 124/1820 [00:11<02:27, 11.48it/s]
  7%|█████▍                                                                         | 126/1820 [00:11<02:29, 11.37it/s]
  7%|█████▌                                                                         | 128/1820 [00:11<02:28, 11.43it/s]
  7%|█████▋                                                                         | 130/1820 [00:11<02:28, 11.36it/s]
  7%|█████▋                                                                         | 132/1820 [00:11<02:28, 11.40it/s]
  7%|█████▊                                                                         | 134/1820 [00:12<02:29, 11.26it/s]
  7%|█████▉                                                                         | 136/1820 [00:12<02:30, 11.16it/s]
  8%|█████▉                                                                         | 138/1820 [00:12<02:33, 10.98it/s]
  8%|██████                                                                         | 140/1820 [00:12<02:39, 10.50it/s]
  8%|██████▏                                                                        | 142/1820 [00:12<02:36, 10.71it/s]
  8%|██████▎                                                                        | 144/1820 [00:13<02:33, 10.89it/s]
  8%|██████▎                                                                        | 146/1820 [00:13<02:31, 11.07it/s]
  8%|██████▍                                                                        | 148/1820 [00:13<02:29, 11.17it/s]
  8%|██████▌                                                                        | 150/1820 [00:13<02:28, 11.26it/s]
  8%|██████▌                                                                        | 152/1820 [00:13<02:26, 11.35it/s]
  8%|██████▋                                                                        | 154/1820 [00:13<02:26, 11.39it/s]
  9%|██████▊                                                                        | 156/1820 [00:14<02:29, 11.15it/s]
  9%|██████▊                                                                        | 158/1820 [00:14<02:32, 10.91it/s]
  9%|██████▉                                                                        | 160/1820 [00:14<02:35, 10.64it/s]
  9%|███████                                                                        | 162/1820 [00:14<02:39, 10.41it/s]
  9%|███████                                                                        | 164/1820 [00:14<02:31, 10.93it/s]
  9%|███████▏                                                                       | 166/1820 [00:15<02:28, 11.13it/s]
  9%|███████▎                                                                       | 168/1820 [00:15<02:27, 11.24it/s]
  9%|███████▍                                                                       | 170/1820 [00:15<02:27, 11.19it/s]
  9%|███████▍                                                                       | 172/1820 [00:15<02:27, 11.16it/s]
 10%|███████▌                                                                       | 174/1820 [00:15<02:26, 11.26it/s]
 10%|███████▋                                                                       | 176/1820 [00:15<02:24, 11.36it/s]
 10%|███████▋                                                                       | 178/1820 [00:16<02:19, 11.81it/s]
 10%|███████▊                                                                       | 180/1820 [00:16<02:20, 11.69it/s]
 10%|███████▉                                                                       | 182/1820 [00:16<02:28, 11.03it/s]
 10%|███████▉                                                                       | 184/1820 [00:16<02:30, 10.88it/s]
 10%|████████                                                                       | 186/1820 [00:16<02:29, 10.91it/s]
 10%|████████▏                                                                      | 188/1820 [00:17<02:30, 10.82it/s]
 10%|████████▏                                                                      | 190/1820 [00:17<02:29, 10.93it/s]
 11%|████████▎                                                                      | 192/1820 [00:17<02:21, 11.51it/s]
 11%|████████▍                                                                      | 194/1820 [00:17<02:21, 11.45it/s]
 11%|████████▌                                                                      | 196/1820 [00:17<02:23, 11.31it/s]
 11%|████████▌                                                                      | 198/1820 [00:17<02:26, 11.09it/s]
 11%|████████▋                                                                      | 200/1820 [00:18<02:24, 11.24it/s]
 11%|████████▊                                                                      | 202/1820 [00:18<02:23, 11.31it/s]
 11%|████████▊                                                                      | 204/1820 [00:18<02:21, 11.42it/s]
 11%|████████▉                                                                      | 206/1820 [00:18<02:20, 11.45it/s]
 11%|█████████                                                                      | 208/1820 [00:18<02:21, 11.38it/s]
 12%|█████████                                                                      | 210/1820 [00:18<02:22, 11.34it/s]
 12%|█████████▏                                                                     | 212/1820 [00:19<02:23, 11.24it/s]
 12%|█████████▎                                                                     | 214/1820 [00:19<02:25, 11.07it/s]
 12%|█████████▍                                                                     | 216/1820 [00:19<02:27, 10.90it/s]
 12%|█████████▍                                                                     | 218/1820 [00:19<02:24, 11.07it/s]
 12%|█████████▌                                                                     | 220/1820 [00:19<02:22, 11.22it/s]
 12%|█████████▋                                                                     | 222/1820 [00:20<02:29, 10.70it/s]
 12%|█████████▋                                                                     | 224/1820 [00:20<02:28, 10.72it/s]
 12%|█████████▊                                                                     | 226/1820 [00:20<02:28, 10.76it/s]
 13%|█████████▉                                                                     | 228/1820 [00:20<02:27, 10.76it/s]
 13%|█████████▉                                                                     | 230/1820 [00:20<02:26, 10.89it/s]
 13%|██████████                                                                     | 232/1820 [00:21<02:26, 10.82it/s]
 13%|██████████▏                                                                    | 234/1820 [00:21<02:20, 11.30it/s]
 13%|██████████▏                                                                    | 236/1820 [00:21<02:20, 11.26it/s]
 13%|██████████▎                                                                    | 238/1820 [00:21<02:20, 11.25it/s]
 13%|██████████▍                                                                    | 240/1820 [00:21<02:21, 11.16it/s]
 13%|██████████▌                                                                    | 242/1820 [00:21<02:23, 10.96it/s]
 13%|██████████▌                                                                    | 244/1820 [00:22<02:25, 10.80it/s]
 14%|██████████▋                                                                    | 246/1820 [00:22<02:26, 10.77it/s]
 14%|██████████▊                                                                    | 248/1820 [00:22<02:20, 11.22it/s]
 14%|██████████▊                                                                    | 250/1820 [00:22<02:18, 11.36it/s]
 14%|██████████▉                                                                    | 252/1820 [00:22<02:19, 11.28it/s]
 14%|███████████                                                                    | 254/1820 [00:23<02:29, 10.48it/s]
 14%|███████████                                                                    | 256/1820 [00:23<02:30, 10.40it/s]
 14%|███████████▏                                                                   | 258/1820 [00:23<02:26, 10.68it/s]
 14%|███████████▎                                                                   | 260/1820 [00:23<02:23, 10.90it/s]
 14%|███████████▎                                                                   | 262/1820 [00:23<02:22, 10.92it/s]
 15%|███████████▍                                                                   | 264/1820 [00:23<02:20, 11.09it/s]
 15%|███████████▌                                                                   | 266/1820 [00:24<02:19, 11.14it/s]
 15%|███████████▋                                                                   | 268/1820 [00:24<02:19, 11.10it/s]
 15%|███████████▋                                                                   | 270/1820 [00:24<02:20, 11.02it/s]
 15%|███████████▊                                                                   | 272/1820 [00:24<02:19, 11.08it/s]
 15%|███████████▉                                                                   | 274/1820 [00:24<02:18, 11.20it/s]
 15%|███████████▉                                                                   | 276/1820 [00:24<02:15, 11.37it/s]
 15%|████████████                                                                   | 278/1820 [00:25<02:16, 11.33it/s]
 15%|████████████▏                                                                  | 280/1820 [00:25<02:16, 11.32it/s]
 15%|████████████▏                                                                  | 282/1820 [00:25<02:20, 10.94it/s]
 16%|████████████▎                                                                  | 284/1820 [00:25<02:29, 10.27it/s]
 16%|████████████▍                                                                  | 286/1820 [00:25<02:28, 10.36it/s]
 16%|████████████▌                                                                  | 288/1820 [00:26<02:27, 10.41it/s]
 16%|████████████▌                                                                  | 290/1820 [00:26<02:29, 10.24it/s]
 16%|████████████▋                                                                  | 292/1820 [00:26<02:28, 10.29it/s]
 16%|████████████▊                                                                  | 294/1820 [00:26<02:24, 10.54it/s]
 16%|████████████▊                                                                  | 296/1820 [00:26<02:23, 10.65it/s]
 16%|████████████▉                                                                  | 298/1820 [00:27<02:19, 10.90it/s]
 16%|█████████████                                                                  | 300/1820 [00:27<02:17, 11.06it/s]
 17%|█████████████                                                                  | 302/1820 [00:27<02:14, 11.25it/s]
 17%|█████████████▏                                                                 | 304/1820 [00:27<02:15, 11.22it/s]
 17%|█████████████▎                                                                 | 306/1820 [00:27<02:14, 11.28it/s]
 17%|█████████████▎                                                                 | 308/1820 [00:27<02:12, 11.39it/s]
 17%|█████████████▍                                                                 | 310/1820 [00:28<02:19, 10.83it/s]
 17%|█████████████▌                                                                 | 312/1820 [00:28<02:22, 10.62it/s]
 17%|█████████████▋                                                                 | 314/1820 [00:28<02:18, 10.90it/s]
 17%|█████████████▋                                                                 | 316/1820 [00:28<02:16, 11.00it/s]
 17%|█████████████▊                                                                 | 318/1820 [00:28<02:15, 11.11it/s]
 18%|█████████████▉                                                                 | 320/1820 [00:29<02:13, 11.27it/s]
 18%|█████████████▉                                                                 | 322/1820 [00:29<02:13, 11.23it/s]
 18%|██████████████                                                                 | 324/1820 [00:29<02:11, 11.34it/s]

In [13]:
df.head(10)

,resume_text,jobs,ats_score
0,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nPosition: Junior PHP Dev...,26.76
1,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nPosition: Junior PHP Dev...,26.76
2,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nJob Summary:\n\nWe are s...,21.37
3,Abhishek Chaudhary \n ac5712916@gmail.com |...,Job Title: Sr. Website UI/UX Designer and Deve...,36.91
4,Abhishek Chaudhary \n ac5712916@gmail.com |...,We are looking for a passionate and enthusiast...,30.80
5,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nJob Title: Software Engi...,27.04
6,Abhishek Chaudhary \n ac5712916@gmail.com |...,Software Tester Intern\n\nAbout Us\n\nWe are ...,20.67
7,Abhishek Chaudhary \n ac5712916@gmail.com |...,About Warpfy\n\nWe are a fast-growing cross-bo...,30.84
8,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nWork from office only\n\...,29.00
9,Abhishek Chaudhary \n ac5712916@gmail.com |...,Company: Weskill Edutech Private Limited\nLoca...,38.33

In [15]:
df.iloc[0][0]

C:\Users\Mahadev\AppData\Local\Temp\ipykernel_2268\2900375399.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]

'Abhishek Chaudhary \n   ac5712916@gmail.com  |  +91-9781673453  |  Punjab, India  \n                                                        \n \nSkills \n        Python  |  kotlin  |  OOPS   | HTML| CSS  | Critical Thinking \n \nProjects \nWeather Prediction App \n                       Python \n• \nIt is used to predict the weather. \n• \nIt can give weather reports manually. \n• \nIt also display’s the current day weather. \n• \nIn this application, API is used. \nCar Karo App      \n   HTML, CSS, JavaScript  \n• \nIt is car booking application where one can book the cab at reasonable prices.  \n• \nSharing and user-friendly application. \n• \nLocation API is used to track the cab. \n• \nPayment method can be both offline and online. \n \n \nCertifications  \n• \nPython Certificate – Nice computers \n \nAchievements  \n• \nDistrict Cricket player \n• \nState karate player. \nEducation  \nD.A.V. Institute of Engineering and Technology                                                               Jalandhar, Punjab, India \nB. Tech Computer Science and Engineering \n                                   2021 - 2025 \nCGPA: 7 \n \nHeights Academy  \n \n \n \n \n \n \n       Hoshiarpur, Punjab, India \nSenior Secondary (PSEB)  \n   \n \n \n \n \n \n                 2020 – 2021 \nPercentage: 93.4% \n \nToddlers Home Study Hall  \n \n \n         \n \n \n                      Hoshiarpur, Punjab, India \nHigher Secondary (PSEB) \n \n \n \n \n \n \n \n \n   2018 - 2019 \nPercentage: 86.4%'

In [16]:
df.iloc[0][1]

C:\Users\Mahadev\AppData\Local\Temp\ipykernel_2268\2309508539.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][1]

'Full job description\nPosition: Junior PHP Developer (Fresher)\nTraining Required: 2–6 months of PHP Training/Internship\nLocation: Mohali (Work from office only)\nEmployment Type: Full-Time\nInterview Mode: In-Person only\n\nAbout the Role\n\nWe are looking for enthusiastic and motivated PHP Freshers who have successfully completed 2–6 months of training in PHP development. The ideal candidate should have a strong understanding of web technologies, databases, and programming concepts, with a passion to grow as a professional web developer.\n\nKey Responsibilities\n\nAssist in developing, testing, and maintaining web applications using Core PHP.\nWork on front-end technologies including HTML, CSS, JavaScript, jQuery, and Bootstrap.\nIntegrate databases using MySQL and write optimized queries.\nSupport senior developers in coding, debugging, and troubleshooting web applications.\nImplement OOPS concepts in PHP for modular and scalable development.\nWork with AJAX for dynamic and interactive web features.\nStay updated with the latest technologies and best practices in web development.\nCollaborate with the team to deliver high-quality projects on time.\nRequired Skills & Knowledge\n\nStrong knowledge of Core PHP.\nHands-on experience in HTML, CSS, JavaScript, jQuery, Bootstrap.\nUnderstanding of MySQL (CRUD operations, joins, queries).\nGood knowledge of OOPS concepts and their implementation in PHP.\nFamiliarity with AJAX for asynchronous requests.\nStrong problem-solving and logical thinking skills.\nEagerness to learn and adapt to new technologies.\nEligibility\n\nCompleted training/internship (2–6 months) in PHP and related technologies.\nB.Tech(CSE/IT)/MCA/BCA or any relevant degree/certification in Computer Science/IT.\nFresh graduates with a good understanding of PHP and web development concepts are encouraged to apply.\nWhat We Offer\n\nOpportunity to work on live projects and gain real-time experience.\nMentorship and guidance from experienced developers.\nA collaborative and growth-oriented work environment.\nCareer progression opportunities within the organization.\nJob Types: Full-time, Permanent, Fresher\n\nPay: ₹8,000.00 - ₹10,000.00 per month\n\nBenefits:\n\nHealth insurance\nPaid sick time\nPaid time off\nProvident Fund\nWork Location: In person'

In [17]:
df.head()

,resume_text,jobs,ats_score
0,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nPosition: Junior PHP Dev...,26.76
1,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nPosition: Junior PHP Dev...,26.76
2,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nJob Summary:\n\nWe are s...,21.37
3,Abhishek Chaudhary \n ac5712916@gmail.com |...,Job Title: Sr. Website UI/UX Designer and Deve...,36.91
4,Abhishek Chaudhary \n ac5712916@gmail.com |...,We are looking for a passionate and enthusiast...,30.80